### PR TITLE
Add SKIP policy to not expect a PROXY header

### LINKED ISSUE #95: CIDR based policy for a simple non-PROXY traffic
I believe I'm not the first one who tries to solve the PROXY PROTOCOL vs no PROXY PROTOCOL traffic problem for a single listener. This is a very common behavior for k8s clusters that use PROXY_PROTOCOL based loadbalancers.

In short, the k8s pods clients local traffic doesn't use PROXY PROTOCOL, therefore accessing the service locally that expects PROXY PROTOCOL fails. There are two dirty solutions for this: route local traffic to the external loadbalancer IP (to add the required header), or fallback due to timeout.

Both options above have flaws: LB adds latency and load, timeout adds latency and acts unpredictably on heavy load.

I know that it's possible to create an extra wrapper around the original Conn, but this would look dirty. I propose to add a new SKIP policy, which will treat a connection as a regular one and it won't trigger proxyproto handlers. The SKIP policy can be defined in a `PolicyFunc` callback.

Objections?

### PR DESCRIPTION
**Pull request by kayrus**
Resolves #95

### CODE REVIEW

**Comment by kayrus** [comment]
@pires could you please take a look on this PR?

**Comment by pires** [comment]
Please, add tests and documentation. I think what you wrote in #95 description is a good starting point.

**Comment by kayrus** [comment]
@pires where should I put the documentation?

**Comment by kayrus** [comment]
@pires is a `SKIP accepts a connection without approaching a PROXY header` comment looks better than `SKIP accepts a connection without a PROXY header`

**Comment by kayrus** [comment]
@pires is there anything else I need to add to the PR?

**Comment by pires** [comment]
I need a couple days to review this. Thank you very much for your contribution.

**Comment by pires** [comment]
Sorry @kayrus but with a recent bump in the Go tooling version(s), tests that spawn go-routines fail to pass `go vet` if they have calls to `Fatalf` and such. Can you, please, work on that?

Other than that, this LGTM!

**Review by pires — CHANGES_REQUESTED** [review]
Sorry @kayrus but with a recent bump in the Go tooling version(s), tests that spawn go-routines fail to pass `go vet` if they have calls to `Fatalf` and such. Can you, please, work on that?

Other than that, this LGTM!

**Comment by kayrus** [comment]
@pires fixed

**Review by pires — APPROVED** [review]
Thanks a lot for your contribution.

**Pull request merged**
