### PR TITLE
Add support for ReadHeaderTimeout

### PR DESCRIPTION
**Pull request by unmarshal**
Set a read deadline when waiting for the PROXY protocol header.

### CODE REVIEW

**Comment by pires** [comment]
I'm under the impression I'm about to learn something here but how can the coverage increase if no tests were implemented? Are the examples added here considered example tests?

**Comment by unmarshal** [comment]
I was scratching my head about the test coverage too. I ended up just removing the examples and moving the https server to the README. I didn't want to restructure your project.

**Comment by pires** [comment]
No, no, no, please, keep the code in the `examples` folder or let's make sure they are testable examples which is so much better than keeping examples in README.md. I am just curious how the hell goveralls reports a 0.7% increment in code coverage 😂

**Comment by unmarshal** [comment]
Sounds good. Will do.

**Comment by unmarshal** [comment]
code coverage didn't increase because of the examples. guessing it has to do with the new lines added when the deadline is set.

**Review by pires — CHANGES_REQUESTED** [review]
Overall LGTM but please remove the binaries (maybe you added them accidentally) and add tests that show that an error is thrown when a client doesn't write the header after a defined amount of time.

**Comment by unmarshal** [comment]
Whoops. Yes, that was a mistake. I will fix that and also add a test. Cheers.

**Comment by unmarshal** [comment]
Sorry about the premature squashing and force pushes. Didn't realize it messed with github's review system.

**Review by pires — APPROVED** [review]
This is great, thank you very much!

**Comment by jefferai** [comment]
@pires I strongly urge you to pick a suitable default for when no read timeout is set. Otherwise you put the onus on library users to know that they have to do this in order to be safe.

**Comment by pires** [comment]
Agreed.

**Pull request merged**
