### PR TITLE
Added example for Client to readme, fixes #3

### LINKED ISSUE #3: An example for a Dialer and Listener is required.
This is a really good library but it's missing examples for a Dialer and a Listener.
IE client and a server service.
I might write one and I was thinking about a simple "echo" client and server.

The server would accept a PROXY TCP protocol connection and will echo back(and log to stdout) if possible the request protocol(TCP4\TCP6 only), src and destination IP:PORT.

The client would open a connection to a PROXY enabled server(Listener) with a specific src and destination IP:PORT (TCP4\TCP6) and will receive the into the socket\connection a line of readable text containing the received IP:PORT.

I have seen an implementation of this but I forgot to save the links so I cannot copy and paste it and I will need to use some CPU to write it.
Any recommendations on where to start?

I have seen this implementation but it's still not sitting well for me
- https://github.com/Freeaqingme/go-proxyproto/blob/master/protocol.go

Other examples:
- https://github.com/armon/go-proxyproto
- https://github.com/kennylevinsen/serve2d
- https://github.com/nabeken/mikoi/blob/master/mikoi.go
- https://github.com/ninchat/go-proxyprotocol
- https://github.com/inkel/viaproxy/blob/master/conn.go
- https://github.com/djmaze/proxy-responder/blob/master/main.go

I wrote a TPROXY Server and Library in golang at:
- https://github.com/elico/go-linux-tproxy

Which has a basic TCP proxy server function that can eventually utilize the PROXY protocol in couple environments.

### PR DESCRIPTION
**Pull request by mschneider82**

### CODE REVIEW

**Review by pires — APPROVED** [review]
AWESOME! 👏

**Comment by mschneider82** [comment]
@pires  you have to bump a new version tag, otherwise the example will not work (only on master), since the WriteTo function is new

**Comment by pires** [comment]
It's fine, I think. Anyways, I'm expecting to tag 0.2.0 as soon as #36 lands ;)

**Comment by pires** [comment]
`0.2.0` is tagged

**Comment by mschneider82** [comment]
@pires go get still downloads v0.1.3, you missed the v in the version please tag it as v0.2.0 instead of 0.2.0

**Comment by pires** [comment]
Damn!

**Comment by pires** [comment]
Fixed!

**Pull request merged**
