### PR TITLE
Stop exporting CRLF and SEPARATOR

### PR DESCRIPTION
**Pull request by emersion**
These are internal V1 details, users of this package shouldn't need
them.

Closes: https://github.com/pires/go-proxyproto/issues/29

### CODE REVIEW

**Comment by emersion** [comment]
Notes:

- I wonder if we should unexport `SplitTLVs` too. Is there a case where users would get raw TLVs and want to split them?
- The `SIGV1`/`SIGV2` variables are left exported because some users might want to manually recognize PROXY headers.

**Comment by pires** [comment]
>     * I wonder if we should unexport `SplitTLVs` too. Is there a case where users would get raw TLVs and want to split them?

There are cases, yes. One example is https://github.com/pires/go-proxyproto/blob/master/tlvparse/ssl.go#L96. Users may have their own code that requires this.

>     * The `SIGV1`/`SIGV2` variables are left exported because some users might want to manually recognize PROXY headers.
Yep!

**Review by pires — APPROVED** [review]
Thank you very much for your contribution.

**Comment by emersion** [comment]
>Users may have their own code that requires this.

Ah, I see, makes sense then!

**Pull request merged**
